### ISSUE TITLE
very good tool !!! I can't get away from it, iI've been using it before. However, when I recently opened it, I found that it was particularly slow, presumably because it did not release the video memory, can you add an option to release the video memory?

### ISSUE THREAD

**Issue by kenic123** [stavsap/comfyui-ollama#10]
t's a very good tool, I can't get away from it, iI've been using it before. However, when I recently opened it, I found that it was particularly slow, presumably because it did not release the video memory, can you add an option to release the video memory?Because when I run it now, it takes up about 4G of video memory, which slows down COMFYUI from 1it/s to 50s/it, I'm in a lot of pain, I hope you can add an option to free up the language model, it's much needed!

**Comment by stavsap** [comment]
Hi @kenic123 , this is just client wrapper to Ollama, Memory config and usage is set by you ollama server.

**Comment by kenic123** [comment]
> Hi @kenic123 , this is just client wrapper to Ollama, Memory config and usage is set by you ollama server.

非常感谢，在你的启发下我已经通过改变OLLAMA环境变量的方法解决了问题，再次感谢！！

**Comment by Latentnaut** [comment]
I found it very slow, and many times stay frozen... what can I do?

**Comment by stavsap** [comment]
just set the keep field to 0, this should release the model from memory after generation.

**Comment by Latentnaut** [comment]
Thank you, it's at 0 already. My experience is that the nodes works well when the Comfy booting is fresh. After a time working on workflows, if I use Ollama it stucks or go very slow. Therefore I have to restart Comfy and try again.

Is this normal?

**Comment by stavsap** [comment]
nope, doesn't sound normal. can you share a workflow you are using ill try to see it on my end?
