### ISSUE TITLE
Update today does not allow to pick model

### ISSUE THREAD

**Issue by taconugget** [stavsap/comfyui-ollama#15]
The new update today kills the ability to add a model. I can usually type in the field "llava" however I can no longer type anything and it just says undefined.

**Comment by taconugget** [comment]
I found a workaround. By retyping the url and port it pulls up the options for model again.

**Comment by stavsap** [comment]
i fixed the refresh issue. please update.

**Comment by taconugget** [comment]
This works. Thanks for the fix Stavsap!

**Comment by Amit30swgoh** [comment]
WHICH FOLDER YOU PUTED THE MODEL?? IN COMFY UI PLEASE SEND SCREENSHOOT NO ONE HELPS ON THAT 
#

**Comment by JimWang151** [comment]
> ![image](https://private-user-images.githubusercontent.com/42430868/344733617-285de90c-1f14-45bd-9760-89ac59062bb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NzU1NDQsIm5iZiI6MTcyNDc3NTI0NCwicGF0aCI6Ii80MjQzMDg2OC8zNDQ3MzM2MTctMjg1ZGU5MGMtMWYxNC00NWJkLTk3NjAtODlhYzU5MDYyYmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDE2MTQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNmQ3NWQyNTBmMTk5NDIzNjRiNzMyZjRkMmZjZTNkZGM1MDhkYzE3NjI3YTJjMmUzMTdkMjA5N2Y3ODFhOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I4x5wbHAf8lsZ_bIpcXkwY5Dj9edZoCoLh1WdTiiopw) unable to choose models where exactley inside the comfyui folder?

same question.
