### ISSUE TITLE
导入失败

### ISSUE THREAD

**Issue by JioJe** [stavsap/comfyui-ollama#21]
![image](https://github.com/stavsap/comfyui-ollama/assets/171318305/e11345fd-a846-4c63-9bd4-8765ff62ee87)

**Comment by JioJe** [comment]
![image](https://github.com/stavsap/comfyui-ollama/assets/171318305/3db00d2f-c9e1-4de3-b6ed-fb3b5d7da978)
sorry!I really want to use it

**Comment by stavsap** [comment]
it seems as ollama module didnt installed, you are using the windows portable version i see, ill check a solution for this.

if you know how to pip install with the portable version just `pip install ollama` you need to activate the portable python in the cli

**Comment by stavsap** [comment]
run the follwoing command in windows cmd in your portable comfy location

`...\ComfyUI_windows_portable\python_embeded>python.exe -m pip install ollama`

**Comment by stavsap** [comment]
have you installed it via manager?

**Comment by JioJe** [comment]
Thanks a lot, I solved this problem by installing ollama in D:\ComfyUI\ComfyUI_windows_portable\python_embeded
