### ISSUE TITLE
The following error was encountered while trying to retrieve the URL: http://127.0.0.1:11434/api/generate

### ISSUE THREAD

**Issue by BayJ233** [stavsap/comfyui-ollama#22]
<img width="919" alt="企业微信20240709-125003@2x" src="https://github.com/stavsap/comfyui-ollama/assets/144195085/7713abfe-ab4a-42f8-bf82-42d063c74961">
<img width="1147" alt="企业微信20240709-124940@2x" src="https://github.com/stavsap/comfyui-ollama/assets/144195085/03b09a7e-ebba-4fdd-8143-e45697787330">

This is my setup. I have installed the Ollama client and successfully run the llama3 model. I don't know why there is this prompt in comfyui? Thank you for your answer

**Comment by stavsap** [comment]
cant reproduce
