### ISSUE TITLE
basic example failed with error 500

### ISSUE THREAD

**Issue by cherishh** [stavsap/comfyui-ollama#24]
I've installed ollama for windows, and I can use it directly just fine:
![image](https://github.com/user-attachments/assets/ffe82d4f-7a8e-4a2e-9db6-a4a0ad5d25d8)
and it's running on 11434
![image](https://github.com/user-attachments/assets/06d97a64-bce0-4b1d-987b-80fb95abcd2c)
but when I try to run the basic example in comfyui, I get a 500 Internal Privoxy Error
![image](https://github.com/user-attachments/assets/03b2512c-f186-4e71-a4b7-80bfb97bd9f8)
![image](https://github.com/user-attachments/assets/01746536-dde0-406e-a98c-311e6d1caf3b)
![image](https://github.com/user-attachments/assets/5e692d37-bc2b-4f45-bdc9-7a564825054a)
and this url: http://127.0.0.1:11434/api/generate indeed cannot work(404 page not found message on page)

What could be the issue here? Any help would be appreciated.

**Comment by stavsap** [comment]
Hi, are you using a node from this repo? i dont have in my vision node `seed` and `control_after_generate`...
