### ISSUE TITLE
Would it allow me to save and read the context as a file?

### ISSUE THREAD

**Issue by mahougigi** [stavsap/comfyui-ollama#25]
I want to save and read the context as a file for the next conversation, but I found that it cannot be saved as txt. Can you help me to do this?

![image](https://github.com/user-attachments/assets/aace92bd-6447-4a84-be65-bdd1a46f8643)

**Comment by httc57** [comment]
Agreed, adding the functionality to save and restore context nodes would be very convenient.  This way, we could continue a conversation where we left off at any time, and the content wouldn’t disappear when restarting ComfyUI.

**Comment by stavsap** [comment]
ill check how to store and load it from a file, you need it in a file for what use case? transfer context between 2 workflows?

**Comment by mahougigi** [comment]
This is a case where I want to complete a complex task through a series of multiple rounds of dialogue. I hope to be able to reroll it step by step. After completing the first round of dialogue, I need to observe the results to make a choice before proceeding to stage two. But I found that when I use advanced nodes, I cannot save the generated context, enable fixed seeds, and after a period of time, the queue nodes will still be re queued. keep_context options have problems that make the service chaotic or worse to stop running.

这是我的示例，我想使用多轮对话完成复杂任务，我希望能够一步一步地播放节点。在第一轮对话后，我需要根据结果进行选择，然后再播放第二轮。但是我发现高级节点有些小问题并不支持这么做。我第一轮对话生成的上下文，并不能切实地保存住，他好像是临时的，我使用固定种子过一段时间或者重启还是这里的上下文就会消失，即使种子固定下一次的结果也截然不同。我尝试使用 keep_context 选项存在问题，会让多轮对话条件混乱或者更糟 Ollama 会停止运行。

虽然我这里可以避免使用上下文，转而使用拼接结果和指令，进行多轮对话。但是我觉得上下文和输出结果分开保存文件和读取文件更灵活有用，重启之后也可以继续之前的复杂工作。


![image](https://github.com/user-attachments/assets/c0cb0a55-9981-4251-8deb-b3fe3b98dd17)



![image](https://github.com/user-attachments/assets/30d71c71-b4a8-47c5-88ed-58a6e55ab5ce)

**Comment by mahougigi** [comment]
The web version of Chat has this historical context feature.

**Comment by stavsap** [comment]
added, check 2 new nodes.

**Comment by mahougigi** [comment]
Very well, thank you

**Comment by mahougigi** [comment]
There are some problems with this

![image](https://github.com/user-attachments/assets/4412ee01-9a5f-480f-9d4b-93128d082766)

**Comment by mahougigi** [comment]
There is also a problem with this, There is no output in the second round of conversation

![image](https://github.com/user-attachments/assets/c5e6242f-9cd3-4ace-968a-2bf34583d79f)

**Comment by stavsap** [comment]
@mahougigi fixed the load file, my bad missed the param name some how, please update.

**Comment by stavsap** [comment]
@mahougigi regarding the empty replay, i am getting the same, it seems that the response from ollama is empty when given context, i updated ollama yesterday. my version of ollama is 0.3.2

what version you using?

**Comment by stavsap** [comment]
iv opened a bug report on this issue

https://github.com/ollama/ollama/issues/6138

lets see if its on their side.

**Comment by mahougigi** [comment]
Thanks for the fix
I reinstalled 0.3.1 and everything works

![image](https://github.com/user-attachments/assets/2937ee1d-e82d-46d9-a159-ffea9a3303ef)

**Comment by mahougigi** [comment]
Very good 0.3.3 is also works
