### ISSUE TITLE
lease help

### ISSUE THREAD

**Issue by missscott** [stavsap/comfyui-ollama#26]
lease help, why can I run Ollama 3.1 locally, but comfyui gives an error when I enter the model name?
![Snipaste_2024-07-28_02-55-25](https://github.com/user-attachments/assets/d6d0311a-0ec1-4ab5-9f61-41c14feab468)
![Snipaste_2024-07-28_02-57-44](https://github.com/user-attachments/assets/71579c14-bf0c-453f-a891-fae37179d6dc)

**Comment by stavsap** [comment]
the llama3.1 LLM dont support vision (image input), you are using a vision node. 

you can use this for vision https://ollama.com/library/llava
