### ISSUE TITLE
无法显示模型

### ISSUE THREAD

**Issue by songhao664** [stavsap/comfyui-ollama#29]
Error occurred when executing OllamaVision:

must provide a model

File "H:\ComfyUI_Max\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "H:\ComfyUI_Max\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "H:\ComfyUI_Max\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "H:\ComfyUI_Max\ComfyUI\custom_nodes\comfyui-ollama\CompfyuiOllama.py", line 72, in ollama_vision
response = client.generate(model=model, prompt=query, images=images_b64, keep_alive=str(keep_alive) + "m")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "H:\ComfyUI_Max\python_embeded\Lib\site-packages\ollama\_client.py", line 125, in generate
raise RequestError('must provide a model')

关闭

**Comment by stavsap** [comment]
you ran a workflow without selecting a model...

**Comment by JimWang151** [comment]
same as me .i am open llava and runing at the backend which can be accessed by the link of: http://127.0.0.1:11434
**_but still get the error msg: must provide a model_**

**Comment by stavsap** [comment]
what model are you selecting from the list?

**Comment by JimWang151** [comment]
after access the url provided by the API DOC:  **http://localhost:11434/api/ps**

it showed the information below:

{
  "models": [
    {
      "name": "llava:latest",
      "model": "llava:latest",
      "size": 5709574144,
      "digest": "8dd30f6b0cb19f555f2c7a7ebda861449ea2cc76bf1f44e262931f45fc81d081",
      "details": {
        "parent_model": "",
        "format": "gguf",
        "family": "llama",
        "families": [
          "llama",
          "clip"
        ],
        "parameter_size": "7B",
        "quantization_level": "Q4_0"
      },
      "expires_at": "2024-08-28T01:49:39.0330076+08:00",
      "size_vram": 5709574144
    }
  ]
}

**Comment by JimWang151** [comment]
> what model are you selecting from the list?

after access the url provided by the API DOC: http://localhost:11434/api/ps

it showed the information below:

{
"models": [
{
"name": "llava:latest",
"model": "llava:latest",
"size": 5709574144,
"digest": "8dd30f6b0cb19f555f2c7a7ebda861449ea2cc76bf1f44e262931f45fc81d081",
"details": {
"parent_model": "",
"format": "gguf",
"family": "llama",
"families": [
"llama",
"clip"
],
"parameter_size": "7B",
"quantization_level": "Q4_0"
},
"expires_at": "2024-08-28T01:49:39.0330076+08:00",
"size_vram": 5709574144
}
]
}

**Comment by JimWang151** [comment]
> what model are you selecting from the list?
in my 'Olama Vision' Node ,the model item showed nothing.

![image](https://github.com/user-attachments/assets/c0c50bb1-db09-4f5e-8be9-0c9edc2f7d8b)

**Comment by JimWang151** [comment]
> what model are you selecting from the list?

after reading the ollama doc and llava API, i think the node function of 'Model Listing' wont work properly.

According to the return JSON ,the model info can been shown before the expired time by the url： http://localhost:11434/api/ps

I think this will give you some tips,because i 've seen many people got this kind of issue.

Thanks for you attention.

This is a great plugin.

**Comment by stavsap** [comment]
are you sure you have ollama running and reachable on localhost? if you go to the browser with this address are you getting response?

![image](https://github.com/user-attachments/assets/40ede603-15af-4bcf-b499-2d7671f6c94b)

**Comment by stavsap** [comment]
> > what model are you selecting from the list?
> 
> after reading the ollama doc and llava API, i think the node function of 'Model Listing' wont work properly.
> 
> According to the return JSON ,the model info can been shown before the expired time by the url： http://localhost:11434/api/ps
> 
> I think this will give you some tips,because i 've seen many people got this kind of issue.
> 
> Thanks for you attention.
> 
> This is a great plugin.

this end point is ps, it shows model in memory, the plugin fetching the available models you have in your ollama server, models you downloaded there. i use python client to do so with different end point.

**Comment by stavsap** [comment]
if you did update to comfy latly try to hard refresh the page

ctrl+shift+r, maybe there some small issues after the UI upgrade...

**Comment by JimWang151** [comment]
There is no problem with the code.
Shut down your proxy or add rule for url localhost/127.0.0.1 .

This issue can be closed.

**Comment by Chateying** [comment]
> > 您从列表中选择什么型号？在我的 'Olama Vision' 节点中，模型项什么也没显示。
> 
> ![图像](https://private-user-images.githubusercontent.com/176783483/361921683-c0c50bb1-db09-4f5e-8be9-0c9edc2f7d8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5Mjk3NTYsIm5iZiI6MTczNDkyOTQ1NiwicGF0aCI6Ii8xNzY3ODM0ODMvMzYxOTIxNjgzLWMwYzUwYmIxLWRiMDktNGY1ZS04YmU5LTBjOWVkYzJmN2Q4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QwNDUwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGE5N2RlOWUyMDJlOTJjZTQ4NjQyNzE3MmI3YTE5YzkxNTc5OWRlMzA0ZDc0OTJmNGNkNTg1NDk5MzY0NjI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rPfOcq-e3vo-ibfnXc2XLabbpSTMqq_rsa_qtWLKtjk)

安装Ollama即可

**Comment by Chateying** [comment]
> > > 您从列表中选择什么型号？在我的 'Olama Vision' 节点中，模型项什么也没显示。
> > 
> > 
> > ![图像](https://private-user-images.githubusercontent.com/176783483/361921683-c0c50bb1-db09-4f5e-8be9-0c9edc2f7d8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5Mjk3NTYsIm5iZiI6MTczNDkyOTQ1NiwicGF0aCI6Ii8xNzY3ODM0ODMvMzYxOTIxNjgzLWMwYzUwYmIxLWRiMDktNGY1ZS04YmU5LTBjOWVkYzJmN2Q4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QwNDUwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGE5N2RlOWUyMDJlOTJjZTQ4NjQyNzE3MmI3YTE5YzkxNTc5OWRlMzA0ZDc0OTJmNGNkNTg1NDk5MzY0NjI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rPfOcq-e3vo-ibfnXc2XLabbpSTMqq_rsa_qtWLKtjk)
> 
> 安装 Ollama即可，需要下载模型
