### ISSUE TITLE
Ollama-YN taking over this node

### ISSUE THREAD

**Issue by Niutonian** [stavsap/comfyui-ollama#30]
Hello, I had this node running without any issues, but lately it stopped working and always shows Ollama-YN no matter what I do, 
It seemed the conflicts is blocking the normal running of this node, 
I have tried uninstalling/reinstalling it many times but it still doesn't work, 

I uninstalled and when I use manager, it is looking for both, 
please let me know how I can get rid of Ollama-YN error, 
thanks

the image below is what I see when I load a workflow that was working before with your node, it is looking for both nodes instead of just one.
![Screenshot 2024-08-06 152310](https://github.com/user-attachments/assets/584f9ace-b4e2-426d-85dd-991b3cd13872)

**Comment by stavsap** [comment]
Just install mine `stavsap`. i dont have any control on the manager behavior for suggestions etc.
