### ISSUE TITLE
Refreshing comfyui (refresh button) sets model to undefined

### ISSUE THREAD

**Issue by brianmlatimer** [stavsap/comfyui-ollama#31]
This is really annoying, as I seem to have to refresh the page, and then manually reset the model type every time I want to refresh. 

Other than fixing this, is there potentially a way to allow the model as an input? I tried but no nodes would connect...

**Comment by JimWang151** [comment]
many people got this issues.

I am now waiting for the solution.

**Comment by JimWang151** [comment]
close your proxy to solve this problem.

the code is perfect.
