### ISSUE TITLE
再次启动comfyui，模型就会不翼而飞？

### ISSUE THREAD

**Issue by JioJe** [stavsap/comfyui-ollama#32]
不知道怎么回事，之前正常使用，现在节点无法读取到模型。
我确定我的ollama是打开的，并且可以从cmd中读取到模型，但无法在comfyui中使用！
![image](https://github.com/user-attachments/assets/f02bd993-3e84-47cd-a7c2-9b6fe9d1f140)
![image](https://github.com/user-attachments/assets/2ba58ab7-c3f9-4e18-a8b6-2984460502d7)
![image](https://github.com/user-attachments/assets/c355c437-694b-4108-a1d4-40634e420432)
![image](https://github.com/user-attachments/assets/f7fc34f4-6b82-4360-a501-02bfd1c11f0d)

**Comment by songhao664** [comment]
看来不是我一个人有这个问题  哈哈

**Comment by xcdh365** [comment]
me to

**Comment by JimWang151** [comment]
me too.

**Comment by stavsap** [comment]
are you sure your ollama is running?

**Comment by JimWang151** [comment]
1、access:http://localhost:11434/ ,web page display:Ollama is running

**Comment by JimWang151** [comment]
I am now solved this issue.
There is no problem with the code.
Shut down your proxy or add rule for url localhost/127.0.0.1 .

This issue can be closed.
