### ISSUE TITLE
i got this issues, how to deal this 

### ISSUE THREAD

**Issue by zmczmc123654** [stavsap/comfyui-ollama#33]
Error fetching Ollama models: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002968AE3C490>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
Error fetching Ollama models: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002968AE3CF10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[comfy_mtb] | INFO -> Found multiple match, we will pick the last D:/SDAI/sd-webui-aki-v4.8\models/SwinIR
['D:\\SDAI\\ComfyUI-aki-v1.3\\models\\upscale_models', 'D:/SDAI/sd-webui-aki-v4.8\\models/ESRGAN', 'D:/SDAI/sd-webui-aki-v4.8\\models/RealESRGAN', 'D:/SDAI/sd-webui-aki-v4.8\\models/SwinIR']
D:\SDAI\ComfyUI-aki-v1.3\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.css
D:\SDAI\ComfyUI-aki-v1.3\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.min.js
Error fetching Ollama models: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002968A8522C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
Error fetching Ollama models: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002968A68BF10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

**Comment by JimWang151** [comment]
Does your llava runing?

**Comment by stavsap** [comment]
is your ollama server running?

if you go in the browser to HTTP://localhost:11434 do you have a response?

**Comment by JimWang151** [comment]
> is your ollama server running?
> 
> if you go in the browser to [HTTP://localhost:11434](HTTP://localhost:11434) do you have a response?

yes,runing.

**Comment by JimWang151** [comment]
I am now solved this issue.
There is no problem with the code.
Shut down your proxy or add rule for url localhost/127.0.0.1 .

This issue can be closed.
