### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by slash1224** [stavsap/comfyui-ollama#34]
The work node is running normally, but the output result is that the image cannot be found,I apologize, but there is no image provided. 

output text:
Please provide the image URL or attach an image for me to assist you with describing its content, color, quality, and style. I'll be happy to help!

How to solve this problem?

**Comment by stavsap** [comment]
can you share screen shot?

**Comment by mike-rowley** [comment]
I am having the same issue.  
![image](https://github.com/user-attachments/assets/6352e77d-478c-4d01-869e-9d8a4a094d8d)

**Comment by mike-rowley** [comment]
I have the same issue, here is a screenshot
![image](https://github.com/user-attachments/assets/eb65ea96-0953-4bc6-99de-4086018051d7)

**Comment by slash1224** [comment]
I have already solved it, but I am not sure how it was resolved. It seems to be related to the OLLAMA model version, as it is necessary to run the image related model.

**Comment by stavsap** [comment]
the screen shot is not this repo nodes, you are installed this https://github.com/wujm424606/ComfyUi-Ollama-YN

**Comment by mike-rowley** [comment]
Not true, I installed your repo from the comfy manager, I checked the README in my custom nodes folder too.
I have also uninstalled and reinstalled your repo, same result

![image](https://github.com/user-attachments/assets/bdb71439-7894-4264-ae39-9487451e24d2)

**Comment by stavsap** [comment]
i saw YN on the node  name, are you sure you using a model supporting vision? like llava? llama shown in the screen shot is not a vision model.

**Comment by mike-rowley** [comment]
I uninstalled and reinstalled the repo and updated ollama and the issue is resolved on my end, thank you.
