### ISSUE TITLE
Comfyui-ollama Node Name Display Error

### ISSUE THREAD

**Issue by delcompan** [stavsap/comfyui-ollama#35]
After installing comfyui-ollama, part of the node name is displayed as another node comfyui-ollama-YN, but I did not install this node.
![Uploading 3.jpg…]()

![2](https://github.com/user-attachments/assets/af165cd1-f614-48af-9e11-6bafd72f70af)

![4](https://github.com/user-attachments/assets/897fa00e-f1d7-4d76-b5b4-f0e083bf3a14)

**Comment by stavsap** [comment]
what nodes? the YN i think its a fork from this repo
