### ISSUE TITLE
about http 503 error code,a suggest for chinese user

### ISSUE THREAD

**Issue by ZzzasdfghjklZzz** [stavsap/comfyui-ollama#37]
it's a very nice Custom ComfyUI Nodes，but when i use it in china,some problem happened.cause chinese user always use proxy to get everything about comfyui on the internet,so when i installed ollama and restart comfyui.
i found the error code in the terminal like:
[HTTP Error 503, the service is unavailable]
then, i am confuse,why?i search solution through google,even chatgpt.finally, when i almost give up,i notice the network proxy log,it show 127.0.0.1:11434 was proxied.
ok,problem should be solved.open the [your comfyui folder path]\python_embeded\Lib\site-packages\ollama\\_client.py, change the python code like:
![image](https://github.com/user-attachments/assets/2c0652c4-89a1-4bbe-a080-6d52171e6fbb)
save your edit,and restart your comfyui.
you will get HTTP Request: GET http://127.0.0.1:11434/api/tags "HTTP/1.1 200 OK"
last,i wish author may add the proxy on/off switch option on the nodes,if you have time.
really thank u,have a nice day,my friend.

**Comment by stavsap** [comment]
you did a change in ollama package, its not my code base.

you can ask for this change from the maintainer of the ollama client. https://github.com/ollama/ollama-python

**Comment by ZzzasdfghjklZzz** [comment]
ok

**Comment by ZzzasdfghjklZzz** [comment]
ok
