### ISSUE TITLE
Seed input don't take int value

### ISSUE THREAD

**Issue by Fictiverse** [stavsap/comfyui-ollama#4]
Hello, first, thank you for this extension, it is working well.
However, the OllamaGenerateAdvance seed input is a float, is it possible to make it an integer or make it compatible with the Seed Evrywhere node please ?

**Comment by stavsap** [comment]
hi, can you link the custom node you referring to?

**Comment by stavsap** [comment]
@Fictiverse i changed the seed to be "int", just update the install via manager or perform git fetch.
