### ISSUE TITLE
generate-advance workflow

### ISSUE THREAD

**Issue by lunatico67** [stavsap/comfyui-ollama#41]
Hi, when I run your example generate-advance workflow I get this error: 

Prompt outputs failed validation
OllamaGenerateAdvance:
- Value -1.0 smaller than min of 0: temperature
- Failed to convert an input value to a FLOAT value: tfs_z, , could not convert string to float: ''
OllamaGenerateAdvance:
- Value -1.0 smaller than min of 0: temperature
- Failed to convert an input value to a FLOAT value: tfs_z, , could not convert string to float: ''

How can I solve it?

**Comment by stavsap** [comment]
HI, there was an update for some fields to float, I have updated the workflow png, you can try again?
