### ISSUE TITLE
Debug option not working

### ISSUE THREAD

**Issue by DanWalsh82** [stavsap/comfyui-ollama#44]
Setting Debug to Disable still results in loads of debug messages in cli.

Simple fix:

In ComyuiOllama.py change lines 75, 215 and 226 from:

        if debug:

to

        if debug == "enable":

**Comment by stavsap** [comment]
ill check it, thanks for pointing this out

**Comment by stavsap** [comment]
committed a fiz

**Comment by DanWalsh82** [comment]
That seems to have fixed it.  Thank you!
