### ISSUE TITLE
Model fetching does not work with ollama 0.3.12

### ISSUE THREAD

**Issue by RaemyS** [stavsap/comfyui-ollama#46]
Hi there,

I'm using ollama version 0.3.12 for windows. With the server running and the llama3.1 model installed and tested, your node was not able to fetch the models. So i could not choose a model from the list to work with your nodes.

I was able to solve the problem for me locally, so i wanted to share the solution with you:

in ComfyuiOllama.py, change the code on line 16 from `url = data.get("url")` to `url = data.get("url" + '/api/tags')`.

It seems, that the ollama api does not longer support this simple approach of just sending a get request to the root url...

To support older installations of ollama, maybe you should firts request the new endpoint and then fall back to the old approach with the root url on 404 (if /api/tags did not already exist in older installations).

Hope this helps :)

Thx for your cool custom nodes and for fixing this issue!

**Comment by stavsap** [comment]
it works fine for me with 0.3.12, cant reproduce. didn't change any code.

![image](https://github.com/user-attachments/assets/4adc0c1a-9f48-4a67-a7f1-6e134cb74e6f)

**Comment by RaemyS** [comment]
Strange... In my case, if i call the URL root without any further path, i only get the "Ollama is running" message from the server:

![image](https://github.com/user-attachments/assets/1b0d959c-cde8-45c2-b3db-dcdd8cd9e5f4)
 Maybe a special behavior with my local installation...

**Comment by stavsap** [comment]
![image](https://github.com/user-attachments/assets/88255207-9f75-42b4-95c5-a1a7031737ab)

data.get("url") is to get base url from the widget then to use ollama python client.

what you doing with postman is correct, but this is done by the python client. maybe try to update the client.

pip install ollama (just be in the right comfy env...)

https://pypi.org/project/ollama/

**Comment by RaemyS** [comment]
I checked the installed ollama client in my venv for comfyui:

![image](https://github.com/user-attachments/assets/d972b07a-d5e0-44ba-b7a9-615649528466)

Version 0.3.3 seems to be latest, according to https://pypi.org/project/ollama/
Since there is no version definition in your requirements.txt, i think this should match? Or do you have another version on your system?

**Comment by stavsap** [comment]
got the same one

![image](https://github.com/user-attachments/assets/af99d55e-4f86-4880-b6d0-6a77f35dd86c)

**Comment by RaemyS** [comment]
Ok, so there seems to be something special on my system. As i found an easy workaround for this locally, please feel free to close this issue, if you want :) Thx for your quick help! :)
