### ISSUE TITLE
The model options cannot pop up a window to enter data

### ISSUE THREAD

**Issue by iwin99** [stavsap/comfyui-ollama#47]
The model options cannot pop up a window to enter data
![question](https://github.com/user-attachments/assets/1f99f30c-7aac-4692-9409-9e2edf318484)

**Comment by iwin99** [comment]
How to solve this problem
ollama has been installed and the model has been installed
![q003](https://github.com/user-attachments/assets/d83bf4c4-cc44-41d3-940a-ae61e5952709)

**Comment by SharkWipf** [comment]
Seems to be an issue related to SwarmUI, at least in my case.
Web console says 404 on `ollama/get_models`.
![image](https://github.com/user-attachments/assets/ed319936-fd9c-4943-a905-77fcebf4c2a3)

However, accessing ComfyUI directly on http://localhost:7821/, this works fine.
I've reported it as a bug on the SwarmUI issue tracker: https://github.com/mcmonkeyprojects/SwarmUI/issues/309

**Comment by mcmonkey4eva** [comment]
Oh, code error at https://github.com/stavsap/comfyui-ollama/blob/main/web/js/OllamaNode.js#L1

Needs to be a relative path, see here https://github.com/comfyanonymous/ComfyUI/pull/867
