### ISSUE TITLE
how to summary video with vlm models

### ISSUE THREAD

**Issue by whmc76** [stavsap/comfyui-ollama#48]

**Comment by stavsap** [comment]
ollama have vlm models? can you reference me to one?

**Comment by whmc76** [comment]
I tried some small snippets but it looks like VLM is just reasoning about each frame and I only get what happened to the last frame of the image

**Comment by whmc76** [comment]
https://pub.towardsai.net/youtube-video-summary-using-ollama-mistralai-96fdeed738e6
i found this and wondering how to apply in comfyui,I think you should be able to handle it haha

**Comment by stavsap** [comment]
the link you provided is to summarize transcript (text), its not video...
