### ISSUE TITLE
可否读取ollama的安装模型列表

### ISSUE THREAD

**Issue by smae08** [stavsap/comfyui-ollama#5]
可否读取ollama的安装模型列表，这样自己打字有点麻烦

**Comment by stavsap** [comment]
english?

**Comment by smae08** [comment]
Can you read the installation model list of Ollama so that typing on your own can be a bit troublesome

**Comment by stavsap** [comment]
you mean a drop down list with available models?

**Comment by smae08** [comment]
yes
