### ISSUE TITLE
What does keep_context do?

### ISSUE THREAD

**Issue by Jonseed** [stavsap/comfyui-ollama#51]
In your example in the README of preserving context in generate chaining, keep_context is turned off (false) on both OllamaGenerateAdvance nodes. So I'm wondering what this keep_context is for. How does it change the context when chaining OllamaGenerateAdvance nodes?

**Comment by stavsap** [comment]
it stores the context from previous queries in the node.

**Comment by Jonseed** [comment]
Is it only storing context for that particular node, if used again in a subsequent queue? Outputting context still works?

![generate-advance](https://github.com/user-attachments/assets/c5d5e74a-242a-4416-8311-9f78e29bba21)

**Comment by stavsap** [comment]
yes its output the context also.

if the keep context is set to `true` then the node will not save context if it is given in the input.

https://github.com/stavsap/comfyui-ollama/blob/ba8c2f9a8ae4a1309079cd8c195e8099002b2ed1/CompfyuiOllama.py#L227
