### ISSUE TITLE
PRE REQUESITES?

### ISSUE THREAD

**Issue by ClothingAI** [stavsap/comfyui-ollama#53]
Hello, 
you did not describe the pre requisites for this custom node to work.

I am assuming:
- Installing Ollama in the local machine, right?
- What else?

**Comment by stavsap** [comment]
yes you would need running ollama instance, its in the reader file

https://github.com/stavsap/comfyui-ollama?tab=readme-ov-file#comfyui-ollama

**Comment by ClothingAI** [comment]
True, I guess I was expecting a section for "what to do to make it run". I made it work since then.
