### ISSUE TITLE
I wish there was some intructions on how to install llama instruct

### ISSUE THREAD

**Issue by ClothingAI** [stavsap/comfyui-ollama#54]
The official ollama page show llama , but nothing about "instruct"? 
How does that work?
Thanks

**Comment by stavsap** [comment]
hi, install ollama from here: https://ollama.com/download

if you need instruct models you can go to model page and press the tags

![image](https://github.com/user-attachments/assets/135a7570-b53d-49b6-8b46-89d4923deb60)

then press the wanted tag, the instruct ones will have instruct word in them, press the tag 

![image](https://github.com/user-attachments/assets/f8dfe116-386e-466b-bbda-1adeee609544)

then you will get to the tag page and you can see the full name of the model in the command area 

![image](https://github.com/user-attachments/assets/294a0459-82da-4a45-8249-d72c4b61199e)

**Comment by ClothingAI** [comment]
Great! But would not installing "just llamma3.1" would include all the sub tags within one single installation? Or am I wrong? I am probably wrong.
While I have you, what are the other "models and TOOLS" that can analyse images other than laava? (I know gpt4 dalle can do it its very expensive so I am looking for cheaper)

**Comment by ClothingAI** [comment]
> you can try to search "vision" in the search bar in ollama web site. that should give you list of vision capable models.

Great. But I mean other that ollama models if you know more stuff?
