### ISSUE TITLE
Ollama vision isn't working

### ISSUE THREAD

**Issue by Autantpourmoi** [stavsap/comfyui-ollama#57]
Ollama generate and ollama generate advance are working but when i want a description of an image with Ollama vision i always got this message with whatever model i use 
I'm happy to help, but I don't see an image. You mentioned "[img-0]" which suggests that there is an image attached to your message, but it's not visible in this text-based interface.

Could you please describe the image to me? What is it about and what objects or features are present in it?
using latest version of ollama 0.3.14 on linux 
`got prompt
[Ollama Vision]
request query params:

- query: describe the image
- url: http://127.0.0.1:11434
- model: llama3.2:latest

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"
[Ollama Vision]
Response:

{'context': [128006,
             9125,
             128007,
             271,
             38766,
             1303,
             33025,
             2696,
             25,
             6790,
             220,
             2366,
             18,
             271,
             128009,
             128006,
             882,
             128007,
             271,
             58,
             1931,
             12,
             15,
             2595,
             12612,
             279,
             2217,
             128009,
             128006,
             78191,
             128007,
             271,
             40,
             2846,
             6380,
             311,
             7664,
             459,
             2217,
             11,
             719,
             358,
             1541,
             956,
             1518,
             832,
             3984,
             13,
             3053,
             499,
             4587,
             4430,
             279,
             2723,
             477,
             7664,
             279,
             2217,
             304,
             810,
             7872,
             779,
             358,
             649,
             3493,
             264,
             4096,
             30],
 'created_at': '2024-10-24T12:00:47.826835955Z',
 'done': True,
 'done_reason': 'stop',
 'eval_count': 37,
 'eval_duration': 291255000,
 'load_duration': 28391425,
 'model': 'llama3.2:latest',
 'prompt_eval_count': 33,
 'prompt_eval_duration': 37051000,
 'response': "I'm happy to describe an image, but I don't see one provided. "
             'Can you please share the link or describe the image in more '
             'detail so I can provide a description?',
 'total_duration': 491076741}
Prompt executed in 1.57 seconds`

**Comment by stavsap** [comment]
llama3.2:latest is not a vision model

**Comment by stavsap** [comment]
i think ollama 0.0.40 beta is only support vision for llama3.2
