### ISSUE TITLE
keep_alive need a '-1' option (keep alive forever)

### ISSUE THREAD

**Issue by morgan55555** [stavsap/comfyui-ollama#59]
Own ollama server is working on single llm model without unloading.
Running comfyui-ollama with keep_alive will cause server to unload a model every time.
We need ability to skip this loads/unloads for better performance.

**Comment by bigcat88** [comment]
just specify "-1", it will be adjusted to "-1m" which is `keep loaded forever` behavior on Ollama API

**Comment by morgan55555** [comment]
Nope, it will change back to 0.
```
"keep_alive": ("INT", {"default": 5, "min": 0, "max": 60, "step": 5}),
```

**Comment by bigcat88** [comment]
Your are right,  ComfyUI frontend will reset it back, missed that.

But when using ComfyUI throw API endpoints it will work(specifying `-1`)

PR to fix this will be very simple, just change `"min": 0` to `"min": -1` and  this will fix it for non-API ComfyUI mode.

**Comment by stavsap** [comment]
i have add the support for this, please try.

**Comment by stavsap** [comment]
feature implemented.
