### ISSUE TITLE
Can you add openwebui auth for this tool?

### ISSUE THREAD

**Issue by morgan55555** [stavsap/comfyui-ollama#61]
Openwebui can handle all calls for ollama api by itself, with customizable model parameters and more.
It has literally same ollama api under the hood ( http://OPENWEBUIADDR/ollama/api ), but [need authorization](https://github.com/open-webui/open-webui/discussions/351).
Can you add authorization for this plugin, somewhere in settings or in node params?

**Comment by stavsap** [comment]
its not in the scope of this project, ollama don't have authn/authz capabilities. open webui got their own thing.
