### ISSUE TITLE
URL and Model load separately

### ISSUE THREAD

**Issue by Khampol** [stavsap/comfyui-ollama#63]
Please, I would like to separe URL and Model load (see pict.). How I could do that? 

![image](https://github.com/user-attachments/assets/6d62ffd6-df27-4e8d-8fa7-eb364590fc9e)

**Comment by MoreColors123** [comment]
I tried this too, because the ollama generate node somtimes resets the model. I used this:

![grafik](https://github.com/user-attachments/assets/34f8a1f3-2fa9-4d8e-bd1a-880528a61e34)

You need to convert the modelwidget into an input by right-click.

**Comment by Khampol** [comment]
Wow, works great, thx  :)
