### ISSUE TITLE
cannot get llava-llama:8b to work

### ISSUE THREAD

**Issue by burritotrex** [stavsap/comfyui-ollama#7]
![image](https://github.com/stavsap/comfyui-ollama/assets/60506524/ded0ffd9-c01e-460d-a912-15cb4b0664cc)

If I try to get the llava-llama:8b or anything else than "llava" to work, it stucks at the point shown on the screenshots above. I am running ollama in docker, llava worked, even though it gave me very bad results for now...

**Comment by smae08** [comment]
docker？？？The URL is incorrect

**Comment by dicksondickson** [comment]
it works out of the box for me with ollama for windows.

**Comment by stavsap** [comment]
can you please share you specs + docker command to run ollama you are using?

also please provide the config of docker (cpu, memory) dedicated.

**Comment by stavsap** [comment]
is this still relevant?

**Comment by dicksondickson** [comment]
I'm guessing OP is encountering permissions problems connecting to the docker container - which is a common thing. I recommend adding a note to the install docs to tell people to install Docker Desktop as that eases a lot of the configuration issues.

**Comment by burritotrex** [comment]
hey there,

sorry haven't worked on my project for the last weeks. I will have another look at it the upcoming days.

I think it might have been a weird bug, where the llava-llama3:8b model kept generating an answer non-stop, so rather a ollama / model related problem. At least that happened by using ollama via cli. But I guess if the answer never finishes, the comfyui node is just waiting for it to finish and therefor seems to be stuck.

**Comment by Amit30swgoh** [comment]
> ![image](https://private-user-images.githubusercontent.com/60506524/331515552-ded0ffd9-c01e-460d-a912-15cb4b0664cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NDgwMjUsIm5iZiI6MTcxOTg0NzcyNSwicGF0aCI6Ii82MDUwNjUyNC8zMzE1MTU1NTItZGVkMGZmZDktYzAxZS00NjBkLWE5MTItMTVjYjRiMDY2NGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDE1Mjg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxNGJjZGRlZjFhNzM3ZmFjNTViNjJkNDA4MDY4NWQ1NmQwZDk0YzdhN2NmOTgyMzdjZjk5N2ZjYWNhOWFkYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N5GSH1BDf0ZVyAeXXTq-8JdreiQgHkHgrJSYGE4nRKM)
> 
> If I try to get the llava-llama:8b or anything else than "llava" to work, it stucks at the point shown on the screenshots above. I am running ollama in docker, llava worked, even though it gave me very bad results for now...

WHICH FOLDER YOU PUTED THE MODEL?? IN COMFY UI PLEASE SEND SCREENSHOOT NO ONE HELPS ON THAT
