### ISSUE TITLE
Llama 3.2 Vision - Takes extremely longer on the second (further) run than the first.

### ISSUE THREAD

**Issue by 925-Studio** [stavsap/comfyui-ollama#77]
It's very strange behavior. It only takes about 3~5 seconds on the first run, but if I queue again (only seeds changed) and the whole computer almost freezes, I can't hardly use my keyboard during the calculation. It seems the node uses the CPU instead of GPU. It didn't happen on LlaVA model. Problem remains after restart ComfyUI. I also tried different quantized model.

Please help. Thanks in advance.

PS: No error info in the terminal.

13600KF, 128GB RAM, 4080S, Linux, Llama 3.2 Vision 11b-Q8 and11b-Q4KM.

**Comment by stavsap** [comment]
the node is just an API proxy to ollama, its what your ollama server doing effect the compute on the host.

**Comment by 925-Studio** [comment]
Thank you for the info and I will close this issue.
