### ISSUE TITLE
Model not found locally, downloading from HuggingFace...

### ISSUE THREAD

**Issue by kenic123** [stavsap/comfyui-ollama#9]
Model not found locally, downloading from HuggingFace... Running the COMFYUI, it's taking up VRAM for a long time, pulling COMFYUI up to 50s/it Running the COMFYUI
运行时出现Model not found locally, downloading from HuggingFace...，长时间占用VRAM，把COMFYUI的速度拉到50s/it

**Comment by dicksondickson** [comment]
Are you using custom nodes that are downloading models from Hugging Face?

**Comment by Amit30swgoh** [comment]
model not found! you did not say where to put the models you also do not gave link to download why?

**Comment by stavsap** [comment]
what models? you need to have ollama server running, ollama manages the models etc...

you can pull and work with with any model you like


https://ollama.com/library

**Comment by smoran** [comment]
> model not found! you did not say where to put the models you also do not gave link to download why?

Just make sure you run the Ollama server prior to opening ComfyUI. If it is already running , simple reneter the IP address of the Ollama server and it will refresh the models list
